version: 1
vaults:
    -
        fsPath: vault
mermaid: true
site:
    copyAssets: true
    assetsPrefix: dendron
    siteHierarchies:
        - welcome
        - dendron
        - pledge
        - public
        - knowledge
        - wikidata
        - cli
        - tools
        - todo
        - writing
        - readlist
        - projects
        - arutam
        - philosophy
        - garage
    siteRootDir: docs
    logo: vault/assets/images/network-5572119__340.png
    siteUrl: 'https://oolonek.github.io/'
    siteLastModified: true
    siteProtocol: https
    usePrettyRefs: true
    gh_edit_link: true
    gh_edit_link_text: Click here to edit this page on Github !
    gh_edit_repository: 'https://github.com/oolonek/dendron'
    gh_edit_branch: main
    gh_edit_view_mode: edit
    title: grndstt's dendron
    author: grndstt
    ga_tracking: G-Q7CCXNMLRB
initializeRemoteVaults: true
journal:
    dailyDomain: daily
    name: journal
    dateFormat: y.MM.dd
    addBehavior: childOfDomain
    firstDayOfWeek: 1
dendronVersion: 0.52.0
dev:
    previewV2Enabled: false
scratch:
    name: scratch
    dateFormat: y.MM.dd.HHmmss
    addBehavior: asOwnDomain
